// =====================================================================
// DAX measure library — GL / P&L Reconciliation Dashboard
// =====================================================================

// ---------- Control totals ----------

ERP Total = SUM(gl_control_totals[erp_total])

Subledger Total = SUM(gl_control_totals[subledger_total])

Variance $ = [Subledger Total] - [ERP Total]

Variance % =
DIVIDE([Variance $], ABS([ERP Total]))

// Flag periods/accounts that breach a materiality threshold — tune this
// to whatever your reconciliation SLA defines as "needs investigation".
Is Out of Tolerance =
VAR Threshold = 0.005  // 0.5% materiality threshold
RETURN
    IF(ABS([Variance %]) > Threshold, 1, 0)

Accounts Out of Tolerance =
CALCULATE(
    DISTINCTCOUNT(gl_control_totals[account_id]),
    FILTER(gl_control_totals, ABS(DIVIDE([Variance $], ABS([ERP Total]))) > 0.005)
)

// ---------- Exceptions ----------

Total Exceptions = COUNTROWS(gl_reconciliation_exceptions)

// ABS so opposite-sign exceptions don't cancel out — this is a magnitude
// ("how many dollars are in question"), not a net position.
Exception Dollar Impact =
SUMX(gl_reconciliation_exceptions,
    ABS(COALESCE(gl_reconciliation_exceptions[variance_amount], gl_reconciliation_exceptions[erp_amount]))
)

Missing Count =
CALCULATE([Total Exceptions], gl_reconciliation_exceptions[exception_type] = "Missing in subledger")

Timing Diff Count =
CALCULATE([Total Exceptions], gl_reconciliation_exceptions[exception_type] = "Timing difference")

Amount Mismatch Count =
CALCULATE([Total Exceptions], gl_reconciliation_exceptions[exception_type] = "Amount mismatch")

Duplicate Count =
CALCULATE([Total Exceptions], gl_reconciliation_exceptions[exception_type] = "Duplicate posting")

// Denominator for Match Rate: the ERP transaction grain, not the
// account x period control-total grain (60 control rows vs ~5,400
// transactions — dividing exceptions by control rows breaks the ratio).
// fact_erp_gl is loaded hidden in the semantic model for exactly this.
ERP Txn Count = COUNTROWS(fact_erp_gl)

// Reconciliation "match rate" — the single number a controller wants on
// a monthly close scorecard.
Match Rate =
VAR TotalErpTxns = [ERP Txn Count]
RETURN
    DIVIDE(TotalErpTxns - [Total Exceptions], TotalErpTxns)


// ---------- FinOps mode (Cloud Chargeback page) ----------

Cloud Billed $ = SUM(focus_coverage[billed_total])

Allocation Coverage % =
DIVIDE(SUM(focus_coverage[allocated_total]), SUM(focus_coverage[billed_total]))

Untagged Spend $ = SUM(focus_coverage[untagged_total])

Cloud Exceptions = COUNTROWS(focus_exceptions)

Cloud Exception $ =
SUMX(
    focus_exceptions,
    ABS(COALESCE(focus_exceptions[variance_amount], focus_exceptions[erp_amount]))
)
